# Generated by Django 6.0.2 on 2026-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Evento')),
                ('tipo_evento', models.CharField(choices=[('feria_empleo', 'Feria de Empleo'), ('reclutamiento_masivo', 'Reclutamiento Masivo'), ('taller', 'Taller'), ('conferencia', 'Conferencia'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Evento')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y Hora de Término')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar o Enlace Virtual')),
                ('descripcion', models.TextField(verbose_name='Descripción del Evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Evento Activo?')),
            ],
            options={
                'verbose_name': 'Evento de Empleabilidad',
                'verbose_name_plural': 'Eventos de Empleabilidad',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
