# Generated by Django 6.0.2 on 2026-07-09 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_idioma'),
        ('profiles', '0002_rename_estado_validacion_empresa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('obligatorio', models.BooleanField(default=False)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('nivel_estudios', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
                ('edad_minima', models.PositiveIntegerField()),
                ('edad_maxima', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Indistinto', 'Indistinto')], max_length=10)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('Concubinato', 'Concubinato')], max_length=20)),
                ('experiencia', models.TextField()),
                ('otros_conocimientos', models.TextField(blank=True, null=True)),
                ('funciones_y_actividades', models.TextField()),
                ('habilidades_y_competencias', models.TextField()),
                ('transporte', models.CharField(choices=[('Transporte público', 'Transporte público'), ('Transporte privado', 'Transporte privado'), ('Transporte propio', 'Transporte propio')], max_length=20)),
                ('oferta_laboral', models.TextField()),
                ('sueldo_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario', models.JSONField()),
                ('entrevistador', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('confidencial', models.BooleanField(default=False)),
                ('area_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='core.areaestudio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='profiles.empresa')),
                ('idiomas', models.ManyToManyField(blank=True, related_name='vacantes', through='vacantes.RequisitoIdioma', to='core.idioma')),
            ],
        ),
        migrations.AddField(
            model_name='requisitoidioma',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante'),
        ),
    ]
