# Generated by Django 6.0.2 on 2026-07-25 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_vacante', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Clave de Vacante')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nombre del Puesto')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada / Concluida')], db_index=True, default='pendiente', max_length=15, verbose_name='Estatus')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('tipo_contratacion', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('indeterminado', 'Contrato Indeterminado'), ('temporal', 'Temporal / Por Proyecto'), ('medio_tiempo', 'Medio Tiempo')], max_length=20, verbose_name='Tipo de Contratación')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('home_office', 'Home Office (Remoto)'), ('hibrido', 'Híbrido')], max_length=15, verbose_name='Modalidad de la Vacante')),
                ('num_candidatos', models.PositiveIntegerField(default=1, verbose_name='Número de Candidatos(as) a Considerar')),
                ('horario_trabajo', models.TextField(verbose_name='Horario y Días de Trabajo')),
                ('nivel_estudios', models.CharField(choices=[('TSU', 'Técnico Superior Universitario'), ('ING_LIC', 'Ingeniería / Licenciatura'), ('MTRIA', 'Maestría')], default='ING_LIC', max_length=10, verbose_name='Nivel de Estudios')),
                ('edad', models.CharField(default='Indistinto', max_length=50, verbose_name='Edad Rango/Buscada')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('indistinto', 'Indistinto')], default='indistinto', max_length=15, verbose_name='Género')),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('indistinto', 'Indistinto')], default='indistinto', max_length=15, verbose_name='Estado Civil')),
                ('es_inclusiva', models.BooleanField(default=False, verbose_name='¿Es vacante inclusiva?')),
                ('capacidades_especiales', models.TextField(blank=True, null=True, verbose_name='Descripción de Capacidades Especiales Consideradas')),
                ('experiencia', models.TextField(verbose_name='Experiencia Previa Requerida')),
                ('conocimientos', models.TextField(verbose_name='Conjunto de Conocimientos (Saberes)')),
                ('habilidades', models.TextField(verbose_name='Habilidades Duras y Blandas')),
                ('actitudes', models.TextField(verbose_name='Actitudes o Valores')),
                ('responsabilidades', models.TextField(verbose_name='Conjunto de Actividades / Responsabilidades del Puesto')),
                ('sueldo_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Mínimo (MXN)')),
                ('sueldo_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Máximo (MXN)')),
                ('salario_a_tratar', models.BooleanField(default=False, verbose_name='¿Salario a tratar en entrevista?')),
                ('prestaciones', models.TextField(verbose_name='Prestaciones y Beneficios')),
                ('incluye_transporte', models.BooleanField(default=False, verbose_name='¿Incluye Transporte?')),
                ('incluye_comedor', models.BooleanField(default=False, verbose_name='¿Incluye Comedor?')),
                ('documentos_requeridos', models.TextField(verbose_name='Documentos Requeridos (Pasaporte, Visa, Licencia, etc.)')),
                ('persona_contacto', models.CharField(max_length=255, verbose_name='Persona de Contacto con la Organización')),
                ('entrevistador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona que realizará la entrevista')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('area_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='core.areaestudio', verbose_name='Área de Estudio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='profiles.empresa', verbose_name='Empresa Empleadora')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Básico'), ('B1', 'B1 - Pre-intermedio'), ('B2', 'B2 - Intermedio'), ('C1', 'C1 - Intermedio Avanzado'), ('C2', 'C2 - Avanzado / Nativo')], default='B1', max_length=2)),
                ('obligatorio', models.BooleanField(default=False)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idioma')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='profiles.egresado')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.vacante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vacante', 'egresado'), name='unique_postulacion')],
            },
        ),
        migrations.CreateModel(
            name='Colocacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_colocacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Colocación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales')),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colocaciones', to='profiles.egresado')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colocados', to='events.evento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colocaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colocados', to='vacantes.vacante')),
            ],
            options={
                'verbose_name': 'Colocación de Egresado',
                'verbose_name_plural': 'Colocaciones de Egresados',
                'unique_together': {('egresado', 'vacante')},
            },
        ),
    ]
