# Generated by Django 6.0.2 on 2026-09-22 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='notas_uth',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de revisión UTH'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('revision_uth', 'En Revisión por UTH'), ('rechazada_uth', 'Rechazada por UTH'), ('enviada_empresa', 'Enviada a Empresa'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='revision_uth', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitoidioma',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_idioma', to='vacantes.vacante'),
        ),
    ]
