# Generated by Django 6.0.2 on 2026-07-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_estado_validacion_empresa_status'),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='profiles.egresado')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.vacante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vacante', 'egresado'), name='unique_postulacion')],
            },
        ),
    ]
