# Generated by Django 6.0.2 on 2026-07-25 00:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono_oficina', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir un prefijo internacional.', regex='^\\+?1?\\d{9,15}$')])),
                ('telefono_celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir un prefijo internacional.', regex='^\\+?1?\\d{9,15}$')])),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('actividad_de_la_empresa', models.CharField(max_length=255)),
                ('campo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='Nombre del contacto')),
                ('cargo_contacto', models.CharField(max_length=100, verbose_name='Cargo del Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(18)])),
                ('cv', models.FileField(blank=True, null=True, upload_to='files/cvs')),
                ('telefono_celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir un prefijo internacional.', regex='^\\+?1?\\d{9,15}$')])),
                ('telefono_casa', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir un prefijo internacional.', regex='^\\+?1?\\d{9,15}$')])),
                ('domicilio', models.TextField(verbose_name='Domicilio Completo')),
                ('nivel_estudios', models.CharField(choices=[('TSU', 'Técnico Superior Universitario'), ('ING_LIC', 'Ingeniería / Licenciatura'), ('MTRIA', 'Maestría')], default='ING_LIC', max_length=10)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('capacidades_especiales', models.TextField(blank=True, null=True, verbose_name='Capacidades Especiales o Discapacidad')),
                ('habilidades', models.TextField(verbose_name='Habilidades Técnicas y Blandas')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='files/docs')),
                ('colocado', models.BooleanField(default=False, verbose_name='¿Egresado Colocado?')),
                ('es_verificado_padron', models.BooleanField(default=False, verbose_name='Verificado contra padrón UTH')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresados', to='core.carrera')),
            ],
        ),
    ]
