# Generated by Django 6.0.2 on 2026-07-06 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(18)])),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir un prefijo internacional.', regex='^\\+?1?\\d{9,15}$')])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresados', to='core.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egresado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos y puede incluir un prefijo internacional.', regex='^\\+?1?\\d{9,15}$')])),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('actividad_de_la_empresa', models.CharField(max_length=255)),
                ('campo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('giro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='core.giro')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='core.sector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
