# Generated by Django 6.0.2 on 2026-07-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='estado_validacion',
            new_name='status',
        ),
    ]
