# Generated by Django 6.0.2 on 2026-09-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronEgresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Matrícula Institucional')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('carrera', models.CharField(max_length=255, verbose_name='Carrera')),
                ('periodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Periodo de Egreso')),
                ('anio_egreso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Año de Egreso')),
                ('estatus_titulacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estatus de Titulación')),
                ('estatus_tsu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estatus TSU')),
                ('etnia_indigena', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etnia Indígena')),
                ('discapacidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Discapacidad')),
                ('genero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Género')),
                ('nivel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel de Estudios')),
                ('tel_escolares', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono Escolares')),
                ('correo_escolares', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Escolares')),
                ('domicilio', models.TextField(blank=True, null=True, verbose_name='Domicilio')),
                ('estado_domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('municipio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio')),
                ('curp', models.CharField(blank=True, max_length=25, null=True, verbose_name='CURP')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de Nacimiento')),
                ('trabaja_actualmente', models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Actualmente trabaja?')),
                ('correo_personal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico Personal')),
                ('telefono_movil', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono Móvil')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Importación')),
            ],
            options={
                'verbose_name': 'Padrón de Egresado',
                'verbose_name_plural': 'Padrón de Egresados',
                'ordering': ['-fecha_importacion', 'matricula'],
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='aprobada', max_length=10),
        ),
    ]
