# Generated by Django 6.0.2 on 2026-10-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_padronegresado_alter_empresa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logotipo Corporativo'),
        ),
    ]
