# Generated by Django 6.0.2 on 2026-02-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin_uth', 'Administrador UTH'), ('egresado', 'Egresado'), ('empresa', 'Empresa')], default='egresado', max_length=255),
        ),
    ]
