# Generated by Django 6.0.2 on 2026-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido_materno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido_paterno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('soporte_ti', 'Soporte TI'), ('admin_uth', 'Administrador UTH'), ('egresado', 'Egresado'), ('empresa', 'Empresa')], max_length=255),
        ),
    ]
