# Generated by Django 6.0.2 on 2026-06-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deactivated',
        ),
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
